<a href="https://colab.research.google.com/github/ioannis-toumpoglou/pytorch-repo/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

PyTorch Tensors are created using torch.Tensor()

https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get Tensor as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with Tensors full of random numbers and then adjust those numbers to better represent the data

In [17]:
# Create a random Tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7968, 0.5129, 0.8093, 0.3799],
        [0.6065, 0.5196, 0.3492, 0.1271],
        [0.3971, 0.4249, 0.7260, 0.6621]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random Tensor with a similar shape of an image Tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [20]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a Tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors like other Tensors

In [24]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating Tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three major issues in PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [26]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,  # Datatype of the Tensor
                               device=None, # What device is the Tensor on - cpu or cuda (gpu)
                               requires_grad=False) # Track the gradience of a Tensor when it goes to numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (attributes)

1. Tensors not right datatype - Get datatype from a Tensor with tensor.dtype
2. Tensors not right shape - Get shape from a Tensor with tensor.shape
3. Tensors not on right device - Get device from a Tensor with tensor.device

In [32]:
# Create a Tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2389, 0.7205, 0.8434, 0.4102],
        [0.3534, 0.6512, 0.2452, 0.6182],
        [0.1102, 0.1565, 0.8190, 0.1111]])

In [33]:
# Find details about Tensor

print(some_tensor)
print(f'Datatype of Tensor: {some_tensor.dtype}')
print(f'Shape of Tensor: {some_tensor.shape}')
print(f'Device Tensor is on: {some_tensor.device}')

tensor([[0.2389, 0.7205, 0.8434, 0.4102],
        [0.3534, 0.6512, 0.2452, 0.6182],
        [0.1102, 0.1565, 0.8190, 0.1111]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply Tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract Tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
  * (3, 2) * (3, 2) won't work
  * (3, 2) * (2, 3) will work
  * (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of **outer dimensions**
  * (2, 3) * (3, 2) -> (2, 2)
  * (3, 2) * (2, 3) -> (3, 3)

In [39]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 237 µs, sys: 40 µs, total: 277 µs
Wall time: 283 µs


tensor(14)

In [43]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 11 µs, total: 77 µs
Wall time: 78.9 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [44]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [45]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the Tensor shape issues, one may manipulate the shape of one of the Tensors using **transpose**. A **transpose** switches the axes or dimensions of a given Tensor.

In [46]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [47]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [48]:
tensor_B.T.shape

torch.Size([2, 3])

In [49]:
# The matrix multiplication operation works when tensor_B is transposed

output = torch.matmul(tensor_A, tensor_B.T)
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [50]:
output.shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc (Tensor aggregation)

In [51]:
# Create a Tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [52]:
# Find the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [53]:
# Find the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [54]:
# Find the mean - the torch.mean() function requires a Tensor of float32 datatype in order to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [55]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [56]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Find the position in Tensor that has the minimum value

x.argmin()

tensor(0)

In [58]:
x[0]

tensor(0)

In [59]:
# Find the position in Tensor that has the maximum value

x.argmax()

tensor(9)

In [60]:
x[9]

tensor(90)

## Reashaping, stacking, squeezing and unsqueezing Tensors

* Reshaping - reshapes an input Tensorto a defined shape
* View - return a view of an input Tensor of certain shape but keep the same memory as the original Tensor
* Stacking - combine multiple Tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove alla `1` dimensions from a Tensor
* Unsqueez - add a `1` dimension to a target Tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Create a Tensor

import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# Change the view

z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Changing z changes x (because a view of a Tensor shares the same memory as the original Tensor)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# Stack Tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
# torch.squeeze() - removes all single dimensions from a target Tensor

print(f'Previous Tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove the extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew Tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [67]:
# torch.unsqueeze() - adds a single dimension to a target Tensor at a specific dim (dimension)

print(f'Previous Tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew Tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [68]:
# torch.permute() - rearranges the dimensions of a target Tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original Tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from Tensors)

Indexing with Pytorch is similar to indexing with NumPy

In [69]:
# Create a Tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [70]:
# Index on the new Tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
# Index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [75]:
# Index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [76]:
# ":" can be used to select all from a target dimension
x[:, 1]

tensor([[4, 5, 6]])

In [77]:
# Get all values of 0th and 1st dimension, but only index 1 from 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [79]:
# Get all values of the 0th dimension, but only the  1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [80]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch Tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

Because of this, PyTorch has functionality to interact with it.

* Data in NumPy array -> PyTorch Tensor => `torch.from_numpy(ndarray)`
* PyTorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [83]:
# NumPy array -> Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
array.dtype

dtype('float64')

In [89]:
# Changing the value of array, how will the Tensor be affected?
array = array + 1

array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 1., 1., 1., 1., 1., 1.]))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [91]:
numpy_tensor.dtype

dtype('float32')

In [92]:
# Changing the Tensor, how will the numpy_tensor be affected?
tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> Tensor operations -> update random numbers to try and make them better representations of the data -> again.. -> again... -> again....`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

What the random seed does is to "flavour" the randomness.


In [93]:
import torch

# Create two random Tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0994, 0.3477, 0.3342, 0.3864],
        [0.1357, 0.6167, 0.4208, 0.4274],
        [0.2594, 0.6914, 0.0970, 0.1695]])
tensor([[0.3057, 0.3617, 0.4969, 0.7381],
        [0.4536, 0.6748, 0.8566, 0.0700],
        [0.5878, 0.4577, 0.6881, 0.4402]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Make some random but reproducible Tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibilty:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running Tensors and PyTorch objects on GPU

GPU = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU
2. Use own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure - these services allow to rent computers on the cloud and access them

For options 2 and 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up . 

Refer to the PyTorch setup documentation:
https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Mon May 15 20:19:32 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [2]:
# Check for GPU access
import torch

torch.cuda.is_available()

True

For PyTorch, since it is capable of running on CPU or GPU, the best practice is to setup device agnostic code:

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [3]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting Tensors (and models) on the GPU

The reason the tensors/models are wanted on the GPU is because using a GPU results to faster computations.

In [7]:
# Create a Tensor (default on CPU)
import torch

tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# Move Tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)

tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors back to the CPU

In [9]:
# If the Tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [10]:
# To fix the GPU Tensor with NumPy issue, first set it to the CPU
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()

tensor_back_to_cpu

array([1, 2, 3])