<a href="https://colab.research.google.com/github/ioannis-toumpoglou/pytorch-repo/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

PyTorch Tensors are created using torch.Tensor()

https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get Tensor as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with Tensors full of random numbers and then adjust those numbers to better represent the data

In [17]:
# Create a random Tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7413, 0.0992, 0.8430, 0.9372],
        [0.4033, 0.4267, 0.1077, 0.8599],
        [0.8866, 0.3084, 0.1476, 0.7268]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random Tensor with a similar shape of an image Tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [20]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
# Create a Tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors like other Tensors

In [24]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating Tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three major issues in PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [26]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,  # Datatype of the Tensor
                               device=None, # What device is the Tensor on - cpu or cuda (gpu)
                               requires_grad=False) # Track the gradience of a Tensor when it goes to numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (attributes)

1. Tensors not right datatype - Get datatype from a Tensor with tensor.dtype
2. Tensors not right shape - Get shape from a Tensor with tensor.shape
3. Tensors not on right device - Get device from a Tensor with tensor.device

In [32]:
# Create a Tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4966, 0.7361, 0.3461, 0.1578],
        [0.7760, 0.3612, 0.7655, 0.9281],
        [0.2724, 0.7751, 0.6061, 0.5758]])

In [33]:
# Find details about Tensor

print(some_tensor)
print(f'Datatype of Tensor: {some_tensor.dtype}')
print(f'Shape of Tensor: {some_tensor.shape}')
print(f'Device Tensor is on: {some_tensor.device}')

tensor([[0.4966, 0.7361, 0.3461, 0.1578],
        [0.7760, 0.3612, 0.7655, 0.9281],
        [0.2724, 0.7751, 0.6061, 0.5758]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [34]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply Tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Subtract Tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
  * (3, 2) * (3, 2) won't work
  * (3, 2) * (2, 3) will work
  * (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of **outer dimensions**
  * (2, 3) * (3, 2) -> (2, 2)
  * (3, 2) * (2, 3) -> (3, 3)

In [42]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [43]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.16 ms, sys: 0 ns, total: 1.16 ms
Wall time: 1.07 ms


tensor(14)

In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.07 ms, sys: 5 µs, total: 1.07 ms
Wall time: 848 µs


tensor(14)

### One of the most common errors in deep learning: shape errors