<a href="https://colab.research.google.com/github/ioannis-toumpoglou/pytorch-repo/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


In [ ]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

PyTorch Tensors are created using torch.Tensor()

https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get Tensor as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with Tensors full of random numbers and then adjust those numbers to better represent the data

In [ ]:
# Create a random Tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1502, 0.1311, 0.3744, 0.4446],
        [0.9198, 0.9971, 0.7957, 0.7417],
        [0.7994, 0.8588, 0.8261, 0.0381]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random Tensor with a similar shape of an image Tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [ ]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a Tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors like other Tensors

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating Tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the three major issues in PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,  # Datatype of the Tensor
                               device=None, # What device is the Tensor on - cpu or cuda (gpu)
                               requires_grad=False) # Track the gradience of a Tensor when it goes to numerical calculations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], 
                             dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (attributes)

1. Tensors not right datatype - Get datatype from a Tensor with tensor.dtype
2. Tensors not right shape - Get shape from a Tensor with tensor.shape
3. Tensors not on right device - Get device from a Tensor with tensor.device

In [ ]:
# Create a Tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5113, 0.9527, 0.8608, 0.4062],
        [0.4617, 0.7189, 0.8067, 0.5116],
        [0.8526, 0.8937, 0.5656, 0.3528]])

In [ ]:
# Find details about Tensor

print(some_tensor)
print(f'Datatype of Tensor: {some_tensor.dtype}')
print(f'Shape of Tensor: {some_tensor.shape}')
print(f'Device Tensor is on: {some_tensor.device}')

tensor([[0.5113, 0.9527, 0.8608, 0.4062],
        [0.4617, 0.7189, 0.8067, 0.5116],
        [0.8526, 0.8937, 0.5656, 0.3528]])
Datatype of Tensor: torch.float32
Shape of Tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply Tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract Tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
  * (3, 2) * (3, 2) won't work
  * (3, 2) * (2, 3) will work
  * (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of **outer dimensions**
  * (2, 3) * (3, 2) -> (2, 2)
  * (3, 2) * (2, 3) -> (3, 3)

In [ ]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.03 ms, sys: 1.69 ms, total: 2.73 ms
Wall time: 2.12 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.8 ms, sys: 0 ns, total: 1.8 ms
Wall time: 1.82 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)  # torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the Tensor shape issues, one may manipulate the shape of one of the Tensors using **transpose**. A **transpose** switches the axes or dimensions of a given Tensor.

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
tensor_B.T.shape

torch.Size([2, 3])

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed

output = torch.matmul(tensor_A, tensor_B.T)
output

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [ ]:
output.shape

torch.Size([3, 3])

## Finding the min, max, mean, sum, etc (Tensor aggregation)

In [ ]:
# Create a Tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min

torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max

torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - the torch.mean() function requires a Tensor of float32 datatype in order to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in Tensor that has the minimum value

x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
# Find the position in Tensor that has the maximum value

x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

## Reashaping, stacking, squeezing and unsqueezing Tensors

* Reshaping - reshapes an input Tensorto a defined shape
* View - return a view of an input Tensor of certain shape but keep the same memory as the original Tensor
* Stacking - combine multiple Tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove alla `1` dimensions from a Tensor
* Unsqueez - add a `1` dimension to a target Tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a Tensor

import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view

z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a Tensor shares the same memory as the original Tensor)

z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack Tensors on top of each other

x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target Tensor

print(f'Previous Tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove the extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew Tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target Tensor at a specific dim (dimension)

print(f'Previous Tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew Tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target Tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original Tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)  # Shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
