<a href="https://colab.research.google.com/github/ioannis-toumpoglou/pytorch-repo/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

In [26]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.0+cu118


In [27]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


## Introduction to Tensors

### Creating Tensors

PyTorch Tensors are created using torch.Tensor()

https://pytorch.org/docs/stable/tensors.html

In [28]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [29]:
scalar.ndim

0

In [30]:
# Get Tensor as Python int
scalar.item()

7

In [31]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [32]:
vector.ndim

1

In [33]:
vector.shape

torch.Size([2])

In [34]:
# Matrix
MATRIX = torch.tensor([[7, 8], 
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [35]:
MATRIX.ndim

2

In [36]:
MATRIX[0]

tensor([7, 8])

In [37]:
MATRIX.shape

torch.Size([2, 2])

In [38]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [39]:
TENSOR.ndim

3

In [40]:
TENSOR.shape

torch.Size([1, 3, 3])

In [41]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random Tensors?

Random Tensors are important because the way many neural networks learn is that they start with Tensors full of random numbers and then adjust those numbers to better represent the data

In [42]:
# Create a random Tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6857, 0.7487, 0.5169, 0.3355],
        [0.7102, 0.4134, 0.0708, 0.6822],
        [0.5248, 0.1706, 0.4005, 0.6896]])

In [43]:
random_tensor.ndim

2

In [44]:
# Create a random Tensor with a similar shape of an image Tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # color channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [45]:
# Create a Tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [46]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
# Create a Tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors like other Tensors

In [53]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Creating Tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])